export const homeData = [
  {
    id: 1,
    name: "The Amazing Spider Man",
    rating: 6.9,
    time: "2hr : 16mins",
    desc: "After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.",
    starring: "Andrew Garfield ,Emma Stone ,Rhys Ifans",
    genres: "Action",
    tags: "Action, Adventures",
    cover: "../images/home1.jpg",
    video: "../video/video1.mp4",
    date: "July 3, 2012",
  },
  {
    id: 2,
    name: "Hulk",
    rating: 5.6,
    time: "2hr : 18mins",
    desc: "Bruce Banner, a genetics researcher with a tragic past, suffers an accident that causes him to transform into a raging green monster when he gets angry. ",
    starring: "Eric Bana,Jennifer Connelly,Sam Elliott",
    genres: "Action",
    tags: "Adventures,Action",
    cover: "../images/home2.jpg",
    video: "../video/video2.mp4",
    date: "17 June 2003",
  },
  {
    id: 3,
    name: "The Avengers",
    rating: 8,
    time: "2hr : 22mins",
    desc: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity. ",
    starring: "Robert Downey Jr,Chris Evans,Scarlett Johansson",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/home3.jpg",
    video: "../video/video3.mp4",
    date: "27 April 2012",
  },
  {
    id: 4,
    name: "Avengers:Endgame",
    rating: 8.4,
    time: "3hr : 1mins",
    desc: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    starring: "Robert Downey Jr ,Chris Evans, Mark Ruffalo",
    genres: "Action",
    tags: "Action, Adventures,",
    cover: "../images/home4.jpg",
    video: "../video/video4.mp4",
    date: "26 April 2019",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/u1.jpg",
    name: "Deadpool & Wolverine",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u2.jpg",
    name: "Venom: The Last Dance",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Captain America: Brave New World",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u4.jpg",
    name: "Kraven the Hunter",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "Thunderbolts",
    time: "2hr : 38mins",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.jpg",
    name: "Guardians of the Galaxy Vol. 3",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "The Marvels",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u1.jpg",
    name: "Latest Movie",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u5.jpg",
    name: "Latest two",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u4.jpg",
    name: "Latest Three",
    time: "2hr : 38mins",
  },
]

export const trending = [
  {
    id: 5,
    name: "Spider-Man: No Way Home",
    rating: 8.7,
    time: "3hr : 01mins",
    desc: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    starring: "Tom Holland,Zendaya,Benedict Cumberbatch",
    genres: "Action",
    tags: "Action, Adventures, Drama",
    cover: "../images/img/slide1.png",
    video: "../video/video5.mp4",
    date: "17 December 2021",
  },
  {
    id: 6,
    name: "Avengers:Infinity War",
    rating: 9.0,
    time: "3hr : 15mins",
    desc: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe. ",
    starring: "Robert Downey Jr,Chris Hemsworth,Mark Ruffalo",
    genres: "Adventures",
    tags: "Adventures,Action,Drama",
    cover: "../images/img/slide2.jpg",
    video: "../video/video6.mp4",
    date: "27 April 2018",
  },
  {
    id: 7,
    name: "Thor: Ragnarok",
    rating: 7.8,
    time: "2hr : 12mins",
    desc: "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela. ",
    starring: "Chris-Hemsworth,Tom-Hiddleston",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/img/slide3.jpg",
    video: "../video/video7.mp4",
    date: "3 November 2017",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "../images/img/slide3.jpg",
    name: "Thor: Ragnarok",
    time: "2hr : 12mins",
  },
  {
    id: 5,
    cover: "../images/img/slide1.png",
    name: "Spider-Man: No Way Home",
    time: "3hr : 01mins",
  },
  {
    id: 1,
    cover: "../images/upcome/u7.jpg",
    name: "The Marvels",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/home4.jpg",
    name: "Avengers:Endgame",
    time: "3hr : 15mins",
  },
  {
    id: 3,
    cover: "../images/home1.jpg",
    name: "TASM1",
    time: "2hr : 16mins",
  },
]
